name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python script.py > result.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          git add result.txt
          git commit -m "Update result.txt"
          git push
